[package]
name = "router-check"
version = "1.0.0"
description = "ZTE Router Dashboard"
authors = ["Cem Cakirlar"]
edition = "2021"

[lib]
name = "router_check"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "router-check"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = ["macos-private-api", "tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
base64 = "0.22"
window-vibrancy = "0.6.0"
md5 = "0.7"
