[package]
name = "router-check-enhanced"
version = "1.0.0"
description = "Enhanced ZTE Router Dashboard in Tauri"
authors = ["Cem Cakirlar"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = ["macos-private-api"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
base64 = "0.22"
tauri-plugin-shell = "2.3.5"
window-vibrancy = "0.6.0"
md5 = "0.7"
