[package]
name = "router-check-enhanced"
version = "1.0.0"
description = "Enhanced ZTE Router Dashboard in Tauri"
authors = ["Cem Cakirlar"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
base64 = "0.22"
tauri-plugin-shell = "2.0.0"
